# make sure all know about this directory
EXTRA_CFLAGS += -Idrivers/net/poweren/include

obj-$(CONFIG_POWEREN_KHEA) += khea.o
khea-objs := khea-main.o khea-netdev.o
khea-objs += khea-ethtools.o khea-misc.o khea-sysfs.o

